
drop table if exists `media151`;
drop table if exists `media152`;
drop table if exists `media153`;
drop table if exists `media154`;
drop table if exists `media155`;
drop table if exists `media156`;
drop table if exists `media157`;
drop table if exists `media158`;
drop table if exists `media159`;
drop table if exists `media160`;
drop table if exists `media161`;
drop table if exists `media162`;
drop table if exists `media163`;
drop table if exists `media164`;
drop table if exists `media165`;
drop table if exists `media166`;
drop table if exists `media167`;
drop table if exists `media168`;
drop table if exists `media169`;
drop table if exists `media170`;
drop table if exists `media171`;







CREATE TABLE IF NOT EXISTS `media151` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) NOT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `rules` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `items` varchar(20) DEFAULT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `impression1` varchar(20) DEFAULT NULL,
  `impression2` varchar(20) DEFAULT NULL,
  `impression3` varchar(20) DEFAULT NULL,
  `impression4` varchar(20) DEFAULT NULL,
  `impression5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media152` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;




CREATE TABLE IF NOT EXISTS `media153` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(20) DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `taget` varchar(20) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `rules` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `items` varchar(20) DEFAULT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `impression1` varchar(20) DEFAULT NULL,
  `impression2` varchar(20) DEFAULT NULL,
  `impression3` varchar(20) DEFAULT NULL,
  `impression4` varchar(20) DEFAULT NULL,
  `impression5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media154` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(20) DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `impression1` varchar(20) DEFAULT NULL,
  `impression2` varchar(20) DEFAULT NULL,
  `impression3` varchar(20) DEFAULT NULL,
  `impression4` varchar(20) DEFAULT NULL,
  `impression5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;




CREATE TABLE IF NOT EXISTS `media155` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(20) DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `items` varchar(20) DEFAULT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media156` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(20) DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `media157` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(20) DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `taget` varchar(20) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `rules` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `items` varchar(20) DEFAULT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `impression1` varchar(20) DEFAULT NULL,
  `impression2` varchar(20) DEFAULT NULL,
  `impression3` varchar(20) DEFAULT NULL,
  `impression4` varchar(20) DEFAULT NULL,
  `impression5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media158` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(20) DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;




CREATE TABLE IF NOT EXISTS `media159` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) NOT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `rules` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `items` varchar(20) DEFAULT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `impression1` varchar(20) DEFAULT NULL,
  `impression2` varchar(20) DEFAULT NULL,
  `impression3` varchar(20) DEFAULT NULL,
  `impression4` varchar(20) DEFAULT NULL,
  `impression5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;




CREATE TABLE IF NOT EXISTS `media160` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `text13` text,
  `actions` varchar(20) DEFAULT NULL,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media161` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `itemname` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `quantity` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `other` text,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media162` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` text,
  `date2` varchar(20) DEFAULT NULL,
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `media162_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_id` int(11) NOT NULL,
  `blogid` int(11) NOT NULL,
  `blog` varchar(255) DEFAULT NULL,
  `blog1` varchar(255) DEFAULT NULL,
  `blog2` text,
  `blog3` text,
  `type` text,
  `price` int(11) NOT NULL,
  `price2` int(11) NOT NULL DEFAULT '0',
  `price3` int(11) NOT NULL DEFAULT '0',
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `blogid` (`blogid`),
  KEY `campaign_blog` (`campaign_id`,`blogid`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media163` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) NOT NULL DEFAULT '',
  `action` varchar(255) NOT NULL DEFAULT '',
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `media164` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `screening` varchar(20) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `impression1` varchar(20) DEFAULT NULL,
  `impression2` varchar(20) DEFAULT NULL,
  `impression3` varchar(20) DEFAULT NULL,
  `impression4` varchar(20) DEFAULT NULL,
  `impression5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `actions` varchar(20) DEFAULT NULL,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media165` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `text13` text,
  `actions` varchar(20) DEFAULT NULL,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media166` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` text,
  `date2` varchar(20) DEFAULT NULL,
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `media166_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_id` int(11) NOT NULL,
  `blogid` int(11) NOT NULL,
  `blog` varchar(20) DEFAULT NULL,
  `blog1` varchar(20) DEFAULT NULL,
  `blog2` text,
  `blog3` text,
  `type` text,
  `price` int(11) NOT NULL,
  `price2` int(11) NOT NULL DEFAULT '0',
  `price3` int(11) NOT NULL DEFAULT '0',
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `media167` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `media168` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `actions` varchar(20) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `impression1` varchar(20) DEFAULT NULL,
  `impression2` varchar(20) DEFAULT NULL,
  `impression3` varchar(20) DEFAULT NULL,
  `impression4` varchar(20) DEFAULT NULL,
  `impression5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `actions2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `media169` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `actions2` varchar(20) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `items` varchar(20) DEFAULT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `media170` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `actions` varchar(20) DEFAULT NULL,
  `actions2` text,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `wheel` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `media171` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_seq` varchar(10) NOT NULL,
  `jpc_seq` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `cue` int(11) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `actions` varchar(30) DEFAULT NULL,
  `phonesystem` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `format1` text,
  `format2` text,
  `rules` text,
  `wheel` varchar(255) DEFAULT NULL,
  `ctr` varchar(255) DEFAULT NULL,
  `date1` int(11) NOT NULL DEFAULT '0',
  `date2` int(11) NOT NULL DEFAULT '0',
  `date3` int(11) NOT NULL DEFAULT '0',
  `date4` int(11) NOT NULL DEFAULT '0',
  `date5` int(11) NOT NULL DEFAULT '0',
  `date6` int(11) NOT NULL DEFAULT '0',
  `date7` int(11) NOT NULL DEFAULT '0',
  `date8` int(11) NOT NULL DEFAULT '0',
  `date9` int(11) NOT NULL DEFAULT '0',
  `date10` int(11) NOT NULL DEFAULT '0',
  `days` varchar(20) DEFAULT NULL,
  `due` text,
  `quantity` varchar(20) DEFAULT NULL,
  `quantity2` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `totalprice` varchar(20) DEFAULT NULL,
  `times` int(11) NOT NULL,
  `items` varchar(20) DEFAULT NULL,
  `others` text,
  `status` int(11) NOT NULL DEFAULT '0',
  `days1` varchar(20) DEFAULT NULL,
  `days2` varchar(20) DEFAULT NULL,
  `days3` varchar(20) DEFAULT NULL,
  `days4` varchar(20) DEFAULT NULL,
  `days5` varchar(20) DEFAULT NULL,
  `price1` varchar(20) DEFAULT NULL,
  `price2` varchar(20) DEFAULT NULL,
  `price3` varchar(20) DEFAULT NULL,
  `price4` varchar(20) DEFAULT NULL,
  `price5` varchar(20) DEFAULT NULL,
  `totalprice1` varchar(20) DEFAULT NULL,
  `totalprice2` varchar(20) DEFAULT NULL,
  `totalprice3` varchar(20) DEFAULT NULL,
  `totalprice4` varchar(20) DEFAULT NULL,
  `totalprice5` varchar(20) DEFAULT NULL,
  `click1` varchar(20) DEFAULT NULL,
  `click2` varchar(20) DEFAULT NULL,
  `click3` varchar(20) DEFAULT NULL,
  `click4` varchar(20) DEFAULT NULL,
  `click5` varchar(20) DEFAULT NULL,
  `impression1` varchar(20) DEFAULT NULL,
  `impression2` varchar(20) DEFAULT NULL,
  `impression3` varchar(20) DEFAULT NULL,
  `impression4` varchar(20) DEFAULT NULL,
  `impression5` varchar(20) DEFAULT NULL,
  `a` varchar(20) DEFAULT NULL,
  `a0` varchar(20) DEFAULT NULL,
  `a1` varchar(20) DEFAULT NULL,
  `a2` varchar(20) DEFAULT NULL,
  `a3` varchar(20) DEFAULT NULL,
  `a4` varchar(20) DEFAULT NULL,
  `a5` varchar(20) DEFAULT NULL,
  `text13` text,
  `items2` varchar(20) DEFAULT NULL,
  `items3` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `status` (`status`),
  KEY `cue` (`cue`),
  KEY `a` (`a`) USING BTREE,
  KEY `a0` (`a0`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
